spring:
  application:
    name: LibraryManagementSystem
  datasource:
    url: jdbc:mysql://localhost:3306/LibraryManagementSystemDb?useSSL=false&serverTimezone=UTC
    username: root
    password: Ahmed1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
server:
  port: 4040

logging:
  level:
    com:
      kilany:
        LibraryManagementSystem=info:
